Refresh:
  # This is the interval (in ticks) between updating
  # the tab header and footer. This limits the animation speed
  Header Footer: 5
  # This is the interval (in ticks) between updating
  # the tab elements and sections. This limits the animation speed
  Tab: 5

Page:
  # This is the amount of elements or slots per column.
  # This includes title and pagination text. Maximum value is 20
  Elements: 20
  # This is the interval (in ticks) between scrolling
  # through tab pages. Recommended to set to a slower speed so
  # the pages don't fly through fast. This will be limited by
  # the update speed of the tab.
  Refresh: 100

Tab:
  # Amount of columns to display. This be set here so we always
  # display that many columns, but just change the content.
  # Make sure to set to how many columns you want to display.
  # If you don't set one of the columns, it will be blank
  Columns: 4

  # The amount of characters per column. This is the limit for
  # text displayed per column before it cuts off. It's also the
  # minimum width for each tab column, meaning it will always be that length
  Width: 50

  # Whether each tab column will have a title, defined for each column.
  # If false, only text elements will be displayed
  # If true, minimum tab width won't work
  Display Titles: true

  # This is the text displayed at the bottom of each tab column
  # when there are multiple pages. Tells you what page
  # you're on
  Page Text: "&7%current_page%&8/&7%max_page%"

  # The default tab to show the player if
  # they don't meet any conditions. Taken
  # from the Tabs section
  Default Tab: default

  # The different tab columns able to be displayed
  Column:
    # Name of the column. Used to register columns
    # and display them
    Information:
      # Column slot to display in
      Slot: 1
      # The title of this tab column
      Title:
        # These are the different animation frames for
        # this text. Each text element is iterated through
        # to create a dynamic animation.
        Animations:
          - "&e&lPlayer Information"
          - "&6&lP&e&llayer Information"
          - "&e&lP&6&ll&e&layer Information"
          - "&e&lPl&6&la&e&lyer Information"
          - "&e&lPla&6&ly&e&ler Information"
          - "&e&lPlay&6&le&e&lr Information"
          - "&e&lPlaye&6&lr &e&lInformation"
          - "&e&lPlayer &6&lI&e&lnformation"
          - "&e&lPlayer I&6&ln&e&lformation"
          - "&e&lPlayer In&6&lf&e&lormation"
          - "&e&lPlayer Inf&6&lo&e&lrmation"
          - "&e&lPlayer Info&6&lr&e&lmation"
          - "&e&lPlayer Infor&6&lm&e&lation"
          - "&e&lPlayer Inform&6&la&e&ltion"
          - "&e&lPlayer Informa&6&lt&e&lion"
          - "&e&lPlayer Informat&6&li&e&lon"
          - "&e&lPlayer Informati&6&lo&e&ln"
          - "&e&lPlayer Informatio&6&ln"
        # This is the interval (in ticks) between updating
        # animation frames. This is limited by the tab update
        # interval
        Interval: 5
      # Text elements to display for this column
      Text:
        # These are the different text elements in
        # the column. Maximum of configured tab elements
        Line1:
          # If this text will scroll across
          # Removes animating text
          Scroll:
            Enabled: false
            # This is the interval (in ticks)
            # between scrolling the text
            Interval: 5
          # These are the different animation frames for
          # this text. Each text element is iterated through
          # to create a dynamic animation.
          Animations:
            - "&ePlayer information displayed here"
            - "&6Player information displayed here"
          # This is the interval (in ticks) between updating
          # animation frames. This is limited by the tab update
          # interval
          Interval: 20
    # Name of the column. Used to register columns
    # and display them
    Server Information:
      # Column slot to display in
      Slot: 2
      # The title of this tab column
      Title:
        # These are the different animation frames for
        # this text. Each text element is iterated through
        # to create a dynamic animation.
        Animations:
          - "&d&lServer Information"
        # This is the interval (in ticks) between updating
        # animation frames. This is limited by the tab update
        # interval
        Interval: 5
      # Text elements to display for this column
      Text:
        # These are the different text elements in
        # the column. Maximum of configured tab elements
        Line1:
          # If this text will scroll across
          # Removes animating text
          Scroll:
            Enabled: false
            # This is the interval (in ticks)
            # between scrolling the text
            Interval: 5
          # These are the different animation frames for
          # this text. Each text element is iterated through
          # to create a dynamic animation.
          Animations:
            - "&ePlayer information displayed here"
            - "&6Player information displayed here"
          # This is the interval (in ticks) between updating
          # animation frames. This is limited by the tab update
          # interval
          Interval: 20

  # These are custom lists to display things
  # like players, faction members etc. It's when
  # you need to repeat elements but have unique placeholders
  # and want to sort them
  Lists:
    # Name of the list. Used to register columns
    # and display them
    Online:
      # Column slot to display in
      Slot: 3
      # The title of this tab column
      Title:
        # These are the different animation frames for
        # this text. Each text element is iterated through
        # to create a dynamic animation.
        Animations:
          - "&a&lOnline Players &2%server_online%"
        # This is the interval (in ticks) between updating
        # animation frames. This is limited by the tab update
        # interval
        Interval: -1
      # What the list consists of. Here put
      # the element. Can put custom ones from addons
      # Types: online_players
      Type: online_players
      # In what order to display elements
      # Put a custom sorter
      # Sorters: distance, number_variable, weight
      #
      # distance: The closest players to you are near the top
      # number_variable: A higher number appears higher
      #                  Taken from 'Sort Variable'
      # weight: Uses weight taken from the player group
      #         See 'Groups'. Higher weight appears at the top
      Sorter: weight
      # This will be used for number_variable
      # to sort by number. Can use placeholders
      # so the value of the placeholder is used
      Sort Variable: ""
      # Text for each element
      Text:
        # If this text will scroll across
        Scroll:
          Enabled: false
          # This is the interval (in ticks)
          # between scrolling the text
          Interval: 5
        # These are the different animation frames for
        # this text. Each text element is iterated through
        # to create a dynamic animation.
        Animations:
          - "%group_format%"
        # This is the interval (in ticks) between updating
        # animation frames. This is limited by the tab update
        # interval
        Interval: 20

  # The different tabs composed of the different
  # tab columns
  Tabs:
    # A tab to display to the player
    # this key is the name
    default:
      # Permission NEEDED to be able to view this tab
      Permission: ""
      # The weight of this tab. This controls the
      # priority this tab is displayed if the player
      # meets overlapping requirements.
      # Higher number means higher priority
      Weight: 1
      # The list of columns displayed in this tab
      # The names are the name of each column.
      Columns:
        - "Information"
        - "Server Information"
        - "Online"
      # The tab header. This is displayed at the top
      # of the tab above all columns
      Header:
        # Text to display in the header
        Text:
          # These are the different text elements in
          # the column. Maximum of configured tab elements
          Line1:
            # If this text will scroll across
            Scroll:
              Enabled: false
              # This is the interval (in ticks)
              # between scrolling the text
              Interval: 5
            # These are the different animation frames for
            # this text. Each text element is iterated through
            # to create a dynamic animation.
            Animations:
              - "&ePlayer information displayed here"
              - "&6Player information displayed here"
            # This is the interval (in ticks) between updating
            # animation frames. This is limited by the tab update
            # interval
            Interval: 20

      # The tab footer. This is displayed at the bottom
      # of the tab below all columns
      Footer:
        # Text to display in the footer
        Text:
          # These are the different text elements in
          # the column. Maximum of configured tab elements
          Line1:
            # If this text will scroll across
            Scroll:
              Enabled: false
              # This is the interval (in ticks)
              # between scrolling the text
              Interval: 5
            # These are the different animation frames for
            # this text. Each text element is iterated through
            # to create a dynamic animation.
            Animations:
              - "&ePlayer information displayed here"
              - "&6Player information displayed here"
            # This is the interval (in ticks) between updating
            # animation frames. This is limited by the tab update
            # interval
            Interval: 20

  # These are the different groups for players
  # These are usually used for sorting and formatting
  Groups:
    # This is the name of the group
    default:
      # Permission needed to have this group
      Permission: ""
      # The weight of this tab. This controls the
      # priority this group has over others if the player
      # meets overlapping requirements.
      # Higher number means higher priority
      # Also means how high the player with this
      # group will be displayed in the tab
      Weight: 1
      # This is what is displayed on the tab
      # when the player has this group. Must be
      # passed as the placeholder %group_format% to
      # take this formatting to a tab column
      Display:
        # If this text will scroll across
        Scroll:
          Enabled: false
          # This is the interval (in ticks)
          # between scrolling the text
          Interval: 5
        # These are the different animation frames for
        # this text. Each text element is iterated through
        # to create a dynamic animation.
        Animations:
          - "&7Member &f%player_displayname%"
        # This is the interval (in ticks) between updating
        # animation frames. This is limited by the tab update
        # interval
        Interval: -1

System:
  # The language file to use for the plugin
  # More language files (if available) can be found in the plugins locale folder.
  Language Mode: en_US