# Mock of config files for my sake

settings:
  # The language file to use for the plugin
  # More language files (if available) can be found in the plugins locale folder.
  locale: en_US

tab:
  # The default tab to show players if
  # they don't meet any requirements
  default: default