name: CustomTab
version: ${project.version}
author: Illuzionz Studios
main: com.illuzionzstudios.tab.CustomTab
description: Custom tablist to display information
api-version: "1.13"
depend:
  - ProtocolLib
softdepend:
  - PlaceholderAPI
  - WorldEdit
  - WorldGuard

permissions:
  tab.command.reload:
    default: op