name: CustomTab
version: ${project.version}
author: Illuzionz Studios
main: com.illuzionzstudios.tab.CustomTab
description: Custom tablist to display information
api-version: "1.17"
depend:
  - ProtocolLib
softdepend:
  - PlaceholderAPI

permissions:
  tab.command.reload:
    default: op
